leopard-js/sb-edit

- package-lock.json
AFAIK this doesn't affect anything in the actual sb-edit library; it just fixes some vulnerabilities in out of date, relatively deep dependencies of jest.
```
added 494 packages from 451 contributors and audited 876444 packages in 18.386s                                        
found 3 high severity vulnerabilities                                                                                  
run `npm audit fix` to fix them, or `npm audit` for details                                                          
```
> Run an audit fix

- src/Block.ts
- src/BlockInput.ts
- src/io/sb3/fromSb3.ts
- src/io/scratch-js/toScratchJS.ts
(PullJosh/scratch-js#42 must be merged before this PR.)
This PR completes support for loading obsolete blocks and adds support for exporting them to scratch-js. Obsolete blocks are defined as the following (mostly copied [from here](https://github.com/LLK/scratch-vm/issues/355#issuecomment-379399646)):
- The counter value is a global value that defaults to zero.
- `counter`: Return the counter value.
- `incr counter`: Increment the counter's value by one.
- `clear counter`: Set the counter value to zero.
- ["loud?"](https://github.com/LLK/scratch-flash/blob/96a2a9a7fca2d042da25dc0d4423900163ab4f33/src/Specs.as#L366): ___. [Its behavior](https://github.com/LLK/scratch-flash/blob/996a2911dd425892f0b4224f5998bce38f964481/src/scratch/ScratchRuntime.as#L1125) is to return whether or not the …
> Obsolete blocks

- src/BlockInput.ts
- src/OpCode.ts
- src/io/sb3/fromSb3.ts
This PR adds only the menus from the extensions whose non-menu opcodes were already present in the list (specifically Music, Video Sensing, and WeDo 2.0).
Incoming soon™ scratchblocks PR will depend on this, since it'll be implementing the blocks and menus from these extensions.
As for the other extensions - there should probably be separate discussion on that before putting work into porting over all of them. (There's like... 10+ now or something! :P)
> Add support for more extension menus

- src/Block.ts
- src/OpCode.ts
- src/__tests__/__snapshots__/compilesb3.test.ts.snap
- src/io/scratch-js/toScratchJS.ts
Turns out this block was missing from the library! I double-checked all the other opcodes I saw listed in scratch-vm and this was the only one missing (besides `event_whentouchingobject`, which was [implemented](https://github.com/LLK/scratch-gui/pull/2265) but hasn't yet been released because of [related issues](https://github.com/LLK/scratch-vm/issues/1532) - I figure we don't need to do anything with that until it's officially released).
The test.sb3 project actually had a "when stage clicked" block in it which thanks to this wasn't showing up in the snapshot, so I updated that. (The snapshot is actually how I spotted this missing block - an `unknown block [event_whenstageclicked]` message in the scratchblocks snapshot, while debugging.)
This must be merged prior to #15.
> Implement event_whenstageclicked block

- src/__tests__/__snapshots__/compilesb3.test.ts.snap
- src/io/scratch-js/toScratchJS.ts
I.e, support reporters in the switch-costume and switch-backdrop blocks.
This removes the "unique costume name" code which fundamentally prevents dyanmic costume switching, since it renames costumes in ways the project source code generally doesn't expect.
@PullJosh since you wrote that code originally, do you think this is a safe change? I don't understand its original purpose myself, so I just replaced it with this simpler code.
This makes PullJosh/scratch-js#45 have effect—without this PR, scripts such as "switch costume to (any reporter)" just get converted to `this.costume = undefined`—but the two PRs are totally independent of each other, merging-wise.
> Support dynamic costume switching

- README.md
- src/BlockInput.ts
- src/Project.ts
- src/__tests__/__snapshots__/compilesb3.test.ts.snap
- src/__tests__/compilesb3.test.ts
- src/io/sb3/fromSb3.ts
- src/io/scratchblocks/toScratchblocks.ts
This PR adds an IO file for exporting to the [scratchblocks](https://scratchblocks.github.io/) format, used [on the official Scratch discussion forums](https://scratch.mit.edu/discuss/) and [as a web-embeddable library](https://github.com/scratchblocks/scratchblocks#usage). It resolves #11.
The new API is `(project).toScratchblocks`, returning an object `{[targetName]: "when green flag clicked..."}`.
Changes in this PR depend on #12, #13, and #16. Those should all be merged prior to this.
> Scratchblocks Export

- src/io/scratch-js/toScratchJS.ts
This probably also makes dynamic key detecting work, since it's not trying to transform the input's value anymore.
Should be merged alongside PullJosh/scratch-js#46.
> Output "left arrow" instead of "left" for scratch-js

- src/__tests__/__snapshots__/compilesb3.test.ts.snap
- src/io/scratch-js/toScratchJS.ts
As corresponding to #17, this PR removes the code which transformed costume names, since we always refer to sounds by string-style accessing anyway (`getSoundByName`, `startSound`, etc). This enables accessing sounds dynamically, e.g. "play sound (pick random 0 to 4)". It also implements the code for `sound_playuntildone` and `sound_playsound` (the same way that PR does).
This should be merged after PullJosh/scratch-js#49, since it stores sounds on the new `target.sounds` property implemented there.
/cc @PullJosh - btw, do you think we should start organizing PRs and commits with prefixes like "scratch-js: ..." or "scratchblocks: ..."? It would help for reading/searching through commits and PRs, and makes it more obvious what's referring to what.
> scratch-js: support dynamic sounds & sound objects

- LICENSE.txt
- package.json
Same deal as PullJosh/scratch-js#50, though here we're changing the license from ISC to MIT, to keep things consistent across libraries.
> License under MIT instead of ISC, and update package.json to match scratch-js

- src/__tests__/__snapshots__/compilesb3.test.ts.snap
- src/io/scratch-js/toScratchJS.ts
Should be merged alongside PullJosh/scratch-js#52, which makes `startSound` into a generator. `startSound` now waits for the specified sound to be completely downloaded and started before continuing to the following code. (`playSoundUntilDone` must still be used to wait for the sound to finish playing as well.)
> scratch-js: yield from startSound()

- src/io/sb3/fromSb3.ts
Sprites currently inherit their audio volume from the stage, instead of having their own distinct volume, like they're supposed to. This PR fixes that.
> sb3: load volume correctly for sprites

- src/io/scratch-js/toScratchJS.ts
Just a minor nitpick in the camel-casing code! This means we'll output names like this:
```js
*affectAtStartOfTheirTeamsTurn(character2)
```
...instead of like this:
```js
*affectAtStartOfTheirTeamSTurn(character2)
//                       ^ !
```
> scratch-js: ignore apostrophes when camel-casing

- src/io/scratchblocks/toScratchblocks.ts
This PR makes the scratchblocks output format handle missing input values without crashing. It also makes `escape` work on non-string (but truthy) values.
> scratchblocks: handle missing values nicely

- src/io/sb3/fromSb3.ts
This PR prevents top-level shadow blocks from being imported into an sb-edit project.
**What are top-level shadow blocks?**
*Shadow blocks* represent any reporter-accepting slot in a Scratch 3.0 block. There are two kinds of shadow blocks: *primitive* and *non-primitive*. Primitive shadow blocks are stored as a simple `[primitiveType, value]` array under a block's `inputs` field; these aren't what we're concerned with here.
What we care about are *non-primitive* shadow blocks. These are stored in much the same way as ordinary blocks - i.e, as entries on a target's `blocks` field. They're distinguishable from normal blocks by their `"shadow": true` property.
(Note: "primitive" and "non-primitive" are only terms that exist within (de)serialization of Scratch 3.0 projects. Other parts of the …
> sb3: don't import top-level shadow blocks

- src/io/scratch-js/toScratchJS.ts
See https://github.com/towerofnix/sb-edit/pull/1 for more info--`isNaN(parseFloat(...))` doesn't accurately determine whether a value can be parsed as a number.
> Use Number cast in optionalToNumber

- .eslintrc.js
- package.json
- src/io/scratch-js/toScratchJS.ts
- src/io/scratchblocks/toScratchblocks.ts
- Fix `npm run lint` to recurse into subdirectories
- Remove old no-longer-applicable tslint rules
- Disable problematic rules
- Make toScratchJS.ts and toScratchblocks.ts pass lint
> Second ESLint pass

- .github/workflows/nodejs.yml
This is the [default node.js workflow](https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml), unmodified. I don't think there's any way to test the workflow before merging, but I'd like to make it a PR rather than a direct commit to master so that you people can look over it first. Let me know if it seems okay!
Resolves #14
> Add automated testing with Github Actions

- .github/workflows/npm-publish.yml
- package.json
- Add Github Action for automatically publishing new releases to npm.
- Remove npm version hooks that automatically create a release on Github. (Too much automation. One fat-fingered command should not immediately create and publish an entire new version of the package.)
> NPM publish process

- .eslintrc.js
This should hopefully prevent any more pesky `console.log`s from sneaking into PRs.
> Enable ESLint no-console rule

- src/BlockInput.ts
- src/Target.ts
- src/__tests__/__snapshots__/compilesb3.test.ts.snap
- src/io/leopard/toLeopard.ts
- src/io/sb3/fromSb3.ts
- src/io/sb3/toSb3.ts
- src/io/scratchblocks/toScratchblocks.ts
**This is a major change to the way sb-edit reads and serializes variables.**
- Fixes #85 
- Fixes #86 
This PR changes `BlockInput.Variable` and `BlockInput.List` so their value is a pair of values (in an object), `{ id: string, name: string }`, instead of one value (just the name). The `fromSb3` deserializing code pulls from the IDs in the actual sb3 file, and all serializing code is updated to respect the new format — most notably, this resolves issues in `toLeopard` surrounding multiple variables existing of different IDs but the same name.
The last commit, af5280ba271a184aa0a218ab7b306a7f2f31377c, adds a final pass to `fromSb3` deserialization so that variables which are never referenced in blocks nor shown as monitors are totally wiped from the code — this is a bit of a presumptuous …
> Reference/resolve variables by ID instead of name

- LICENSE.txt
- package-lock.json
- package.json
License updates includes bringing the copyright dates up to 2023 (am I allowed to do that for you two? LOL) and using my main semi-professional name and current email, package.json is updated to 0.13.10.
A quick pass across the open PRs shows this covers everything Dependabot brought up, and npm audit reports zero vulnerabilities. Tests still passing locally.
Made sure to pass all this through Node 12 since that's the version `.github/workflows/nodejs.yml` is configured for!
```zsh
npm install jest@27.5.1
npm install ts-jest@27.5.1
npm install @types/jest@27.5.2
npm install @types/jszip@3.4.1
npm install @types/prettier@1.19.1
npm install @typescript-eslint/eslint-plugin@2.34.0
npm install @typescript-eslint/parser@2.34.0
npm install eslint-config-prettier@6.15.0
npm install …
```
> Dependency & license updates + 0.13.10 release

- src/io/leopard/toLeopard.ts
For standalone sharing of projects, it's convenient to be able to package Leopard's library files right in the same folder as generated Leopard project source. This enables that use case by respecting `leopardJSURL` and `leopardCSSURL` values which are neither external (e.g. `https://unpkg.com/..."`) nor absolute/root-relative (e.g. `/leopard.min.css`). If such a relative path is provided, e.g. `leopard.min.css` or `lib/leopard.min.js`, toLeopard will automatically supply the appropriate `./` or `../` prefix when importing the path in generated source.
Manually tested with custom local paths `leopard.min.js` and `foo%20bar%20baz/leopard.min.js` and snapshot-tested with the default unpkg values.
This is a standalone change which doesn't support any other PRs.
> toLeopard: Support relative "packaged" leopard library paths

- src/__tests__/__snapshots__/compilesb3.test.ts.snap
- src/io/leopard/toLeopard.ts
This PR makes `toLeopard` represent the initial rotation style (which is already represented in IR and loaded by `fromSb3`).
- Resolves #117.
Implementation notes:
* Although we convert *to* the same `Sprite.RotationStyle.ALL_AROUND`/etc value both in block and initial-state serialization, we're mapping *from* different values. (sb3 block inputs like "all around" or "don't rotate" in the former, sb-edit values like "normal" or "none" in the latter.) Accordingly, it wasn't appropriate to introduce a constant mapping reused by both — but it's definitely a bit weird that sb-edit represent the input for "set rotation style" with the same values it uses for a sprite's initial rotation style.
* I had to change the way we stringify sprites to support including an arbitrary expression in the …
> toLeopard: Serialize initial rotation style

- src/io/leopard/toLeopard.ts
This pull request cleans up the code style contained by and surrounding `blockToJS` in a number of fairly high-impact ways, which together make it far easier to incrementally edit block definitions, compare one block to another, and generally read and understand the codebase. See individual commits; in summary:
* Calls to `inputToJS` are basically never inlined as part of the `blockSource` template strings anymore; instead, they're defined in temporary variables, each on its own line, immediately above. This gets rid of the question of "is it worth it *enough* to store this input on a variable?" (always yes) and avoids some really brutal line breaking on particularly long template strings.
* Every `case OpCode.category_op` now gets a proper block scope, i.e. `case OpCode.foo: { ... }`. …
> toLeopard: Code style cleanup for blockToJS & related functions

- src/io/leopard/toLeopard.ts
We broke this [in December](https://github.com/leopard-js/sb-edit/pull/124/commits/c527dda5da5aa46add80e898affba2317770178d#diff-53bcd905a44c89be07db03a8803fe1d8caa6511fe69441ec095f627eafcc5dd4R1381), and since, then the "touching mouse" and "touching edge" boolean blocks have been serialized to:
```js
this.touching(mouse)
this.touching(edge)
// instead of
this.touching("mouse")
this.touching("edge")
```
This PR fixes that!
I'm using `JSON.stringify` instead of just e.g. `"\"mouse\""` because it conveys the same meaning as other general uses, including e.g. [`spriteInputToJS`](https://github.com/towerofnix/sb-edit/blob/c527dda5da5aa46add80e898affba2317770178d/src/io/leopard/toLeopard.ts#L541-L543) and [`increase`](https://github.com/towerofnix/sb-edit/blob/c527dda5da5aa46add80e898affba2317 …
> toLeopard: Fix touching edge/mouse block

- src/__tests__/__snapshots__/compilesb3.test.ts.snap
- src/io/leopard/toLeopard.ts
Self-explanatory. This is the function defined in leopard-js/leopard#188 / leopard-js/leopard#114 and should be merged/released after that pull request.
> toLeopard: Add support for "if on edge, bounce"

- README.md
- package-lock.json
- package.json
- src/cli/index.ts
- tsconfig.json
Closes #128. **Allows importing a .sb3 file and generating a leopard folder or zip directly from the CLI.** I haven't implemented .sb3 output yet for the sake of time/effort. (And because .sb3 is currently the only allowed input method so it would be mostly useless.)
Example output:
I also did my best to make the errors look nice:
> Create CLI that can convert sb3 to leopard or leopard-zip

- src/io/leopard/toLeopard.ts
Development:
- Fixes #133 
- Fixes #134 
- Fixes #136
- Fixes #139 
- Resolves #135 
- Towards leopard-js/leopard#196
Addresses the stuff above! Notable details:
* We've moved these lists, still hard-coded, into top-level constants, rather than embedding them right inside the `toLeopard` function. This makes them more convenient to locate and edit, and separates particularly word-based data from actual conversion logic.
* We've updated and added new documentation strings to relevant top-level constants. These hopefully offer some improved clarity — particularly useful since these are important lists to keep maintained!
* We've renamed `uniqueNameGenerator` to `uniqueNameFactory` because generator functions and factory functions are different things, and this is the latter. (Best not to …
> toLeopard: Fixes and improved clarity for unique-name behavior

- src/cli/index.ts
- tsconfig.json
This PR adds a `-t` / `--trace` CLI option which enables showing the log for unknown errors. It's not necessarily meant to be used by users, moreso just a convenience for us debugging problems.
It also enables source map generation in tsconfig.json. I believe these would be included in the NPM package, which I think is standard practice. Node.js (when running sb-edit) doesn't actually do anything with source maps without providing the `--enable-source-maps` option, typically via an environment variable.
> Add -t, --trace CLI option; enable TypeScript source maps

- src/io/sb3/fromSb3.ts
- src/io/sb3/interfaces.ts
Development:
- Resolves #143 
- Towards #141 (specific project)
See #143 for some technical discussion.
Best to view the commits separately, as they are independent changes, though they affect the same area of code.
* Makes undefined (missing) `next` on blocks in a project.json not crash `fromSb3`. This may be a omission by a minifier used in the demo project, rather than something Scratch itself will ever serialize, though Scratch handles deserializing undefined `next` just fine, so sb-edit should too.
* Improves some code clarity. `blockWithNext` is sometimes called without its `parentId` argument so we just make it `parentId?: string` instead of `parentId: string | undefined`. And `getBlockScript`, previously called once for each script in a target, is now called just once for each …
> fromSb3: Fix loading undefined sb3Block.next

- src/cli/index.ts
Enables testing a custom Leopard build locally, or providing any other alternate Leopard library host.
The default value is the same one that is used by default in [`toLeopard.ts`](https://github.com/leopard-js/sb-edit/blob/9b0f978422d8c0c55918267f7721ff00cb575453/src/io/leopard/toLeopard.ts#L405-L406). It would be nice not to duplicate this definition, but unless toLeopard defined it as an export (this would probably be awkward) or stops providing a default at all, it is what it is.
This option is used in both leopard and leopard-zip output formats, and ignored in other formats.
Only fully qualified URLs are supported, i.e. you can't just do `/leopard/dist`. This is to make the output folder work regardless where it's hosted (provided the specified URL is accessible there), and to avoid …
> Add "--leopard-url" CLI option
